### ISSUE TITLE
puppeteer 라이브러리 Firebase 연동 에러

### ISSUE THREAD

**Issue by CT-1326** [CT-1326/ChannelBOT#1]
`functions[bus(asia-northeast1)]: Deployment error.
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (/srv/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/puppeteer/lib/BrowserFetcher.js:21:17)`

**Comment by stories2** [comment]
![puppeteer](https://user-images.githubusercontent.com/16532326/80550927-ae76b300-89fc-11ea-97a6-7947fbf84001.png)

구 버전에서 정상작동 확인됨 `1.7.0`

```
npm i -save puppeteer@1.7.0
```

대신 메모리 부족 문제가 생길 수 있어 아래와 같이 최소 동작 메모리 양을 늘려주어야 함.

```
const runtimeOpts = {
    timeoutSeconds: 60,
    memory: '512MB'
  }
exports.test = functions.runWith(runtimeOpts).region('asia-northeast1').https.onRequest(testApi)
```

[레퍼런스](https://medium.com/@ebidel/puppeteering-in-firebase-google-cloud-functions-76145c7662bd)

**Comment by stories2** [comment]
관련 [이슈](https://github.com/puppeteer/puppeteer/issues/5687)
